rentApp/config/routes.rb
Rails.application.routes.draw do

#USERS
  resources :users
  get '/users/:id', to: 'users#show'
  get '/properties', to: 'properties#index', as: 'home'
  get '/properties/:id', to: 'properties#show'
  get '/', to: 'properties#search'
#SESSIONS
  get "/signin", to: "sessions#new", as: "signin"
  post "/sessions", to: "sessions#create"
  delete "/logout", to: "sessions#delete"

  #REVIEWS
  resources :reviews

  #Votes
  put "/properties/:id/reviews/:id/like", to: "reviews#upvote", as: "like_reviews"
  put "/properties/:id/reviews/:id/dislike", to: "reviews#downvote", as: "dislike_reviews"

  #PROPERTIES
  resources :properties do
    resources :reviews

    # get :property_id, to: "reviews#new"
    # post :property_id, to: "reviews#create"
  end
  get "properties/:id/reviews", to: "properties#reviews"

end

rentApp/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
     can :manage, User, :active => true, :user_id => user.id
  end
end

rentApp/app/models/property.rb
class Property < ActiveRecord::Base
  has_many :reviews, :dependent => :destroy



  geocoded_by :streetaddress
  after_validation :geocode
end

rentApp/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :property
  acts_as_votable
end

rentApp/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews
  # validates :email, presence: true, uniqueness: true, length: { minimum: 6 }
  # validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  # validates :first_name, :last_name, presence: true
  # validates :password, presence: true

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end
end

rentApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_url, :alert => exception.message
end

# def search
#   if params[:search]
#     @properties = Property.search(params[:search])
#   else
#     @properties = Property.all
#   end
# end

end

rentApp/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

def index
  @properties = Property.all
  @hash = Gmaps4rails.build_markers(@properties) do |property, marker|
      marker.lat property.latitude
      marker.lng property.longitude
      property_link = view_context.link_to property.streetaddress, property_path(property)
      marker.title property.streetaddress
      marker.infowindow "<h4><u>#{property_link}</u><h4>
                            <i>#{property.price}</i>"
    end
  render :index
end

def show
  if current_user == nil
    flash[:error] = "Please login to view more about this property"
    redirect_to "/properties"
  else
  @property = Property.find(params[:id])
  @user = current_user
  @review = @property.reviews
  @reviews = Property.find(params[:id]).reviews
  render :show
  end
end


def reviews
  @reviews = Property.find(params[:id]).reviews
  @property = Property.find(params[:id])
end

def search
  @properties = Property.all
  render :search
end

private

def property_params
  params.require(:property).permit(:streetaddress, :city, :state, :latitude, :longitude, :img, :spec, :price, :sqft, :user_id)
end

end

rentApp/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
    @property = Property.find_by_id(params[:property_id])
    render :index
  end

  def new
    @review = Review.new
    @property = Property.find_by_id(params[:property_id])
    render :_new
  end

  def create
    review_params = params[:review]
    review = Review.new({title: review_params[:title], text: review_params[:text]})
    if review.save
      property = Property.find(params[:property_id])
      property.reviews << review
      current_user.reviews << review
      if property.save && current_user.save
        redirect_to property_path(property.id)
      else
        redirect_to new_property_review_path
      end
    else
      redirect_to new_property_review_path
    end
  end

  def show
    @review = Review.find(params[:id])
    @property = @review.property_id
    @first_name = @review.user.first_name
    render :show
  end

  def edit
    @review = Review.find(params[:id])
    authorize! :manage, @review
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    authorize! :manage, @review
    @review.update(review_params)
    redirect_to '/reviews/#{@review.id}'
  end

  def destroy
    @review = Post.find(params[:id])
    authorize! :manage, @review
    property = Property.find(params[:property_id])
    @review.destroy
    redirect_to property_path(property.id)
  end

  def upvote
    @review = Review.find(params[:id])
    @review.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @review = Review.find(params[:id])
    @review.downvote_by current_user
    redirect_to :back
  end

  private

  def review_params
    params.require(:review).permit(:title, :text, :user_id, :property_id)
  end



end

rentApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.confirm(user_params)
    if @user
      login(@user)
      redirect_to "/"
    else
      flash[:error] = "The password or e-mail entered is incorrect. Please try again"
      redirect_to signin_path
    end
  end

  def delete
    logout
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

rentApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]

  def index
    @user = User.all
    render :index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Hello, #{@user.first_name}! Welcome to Rent13!"
      login(@user)
      redirect_to '/'
    else
      flash[:error] = @user.errors.full_messages.join("----")
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    render :show
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if current_user == @user
      @user.update_attributes(user_params)
      if @user.save
        redirect_to '/users/#{@user.id}'
      else
        redirect_to '/users/#{@user.id}/edit'
      end
    else
      redirect_to "/"
    end
  end

  def reviews
    @reviews = User.find(params[:id]).reviews
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :hometown, :password, :description, :sociallink)
  end

end

rentApp/app/helpers/application_helper.rb
module ApplicationHelper
end

rentApp/app/helpers/properties_helper.rb
module PropertiesHelper
end

rentApp/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rentApp/app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to '/'
    end
  end

  def logout
    session.delete(:user_id)
    @current_user = session[:user_id] = nil
  end
  
end

rentApp/app/helpers/users_helper.rb
module UsersHelper
end

rentApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>RentApp</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href='http://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>
  <script src="2/ninja-slider.js" type="text/javascript"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'animated-text', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'animated-jquery', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAL7ikXN6oM1w89W1HYT_JzA6MJjds79bU"></script>
  <script type="text/javascript" charset="UTF-8" src="http://maps.google.com/maps-api-v3/api/js/25/8/geocoder.js?key=AIzaSyAL7ikXN6oM1w89W1HYT_JzA6MJjds79bU
"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<script src="https://use.fontawesome.com/7ca09aa2f1.js"></script>
  <!-- Javascript -->
</head>
<body>
  <nav class="black">
      <div class="navbar-wrapper container">
        <a href="/" class ="brand-logo class"><strong>Rent<span id="logo13">13</span></strong></a>

        <ul class="right" id="right">
        <% if session[:user_id].nil? %>
          <li><%= link_to "Login", signin_path %></li>
          <li><%= link_to "Create Account", new_user_path %></li>

        <% else %>
          <li><%= link_to "Properties", properties_path %></li>
          <li><%= link_to "Profile", user_path(current_user[:id]) %></li>
          <li><%= link_to "Log Out", logout_path, method: "delete" %></li>

        <% end %>
      </ul>

      </div>
    </nav>

<%= yield %>



</body>
</html>

rentApp/app/views/properties/index.html.erb
<div>
 <div id="map"></div>
</div>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
markers = handler.addMarkers(<%=raw @hash.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
handler.getMap().setZoom(4);
});
</script>

rentApp/app/views/properties/search.html.erb
<div id="homeBack">
  <div id='searchH1'>
    <div>
      <% if session[:user_id].nil? %>
      <h1 class="jumbo">Rent<span id="logo13">13</span></h1>
        <p id="quotes" class="jumbo">Making the world a better place one review at a time</p>
        <p id="quotes" class="jumbo">Let us help you find your perfect home</p>
      </div>
      <% else %>
      <h1 class="jumbo">Rent<span id="logo13">13</span></h1>
        <p id="quotes1" class="jumbo">Making the world a better place one review at a time</p>
        <p id="quotes" class="jumbo">Let us help you find your perfect home</p>
      </div>
    <button class="btn" id="searchBtn">
      <a href="/properties">Check Out Our Properties</a>
    </button>
    <% end %>
    <div id="see"></div>
  </div>
  </div>

rentApp/app/views/properties/show.html.erb
  <section id="coverphoto">
    <div class="container row">
  <div class="col l12 s12">
    <div class="card-panel" id="topPhoto">
    <img src="<%= @property.img %>" id="covPic">
  </div>
</div>
</div>
</section>

<div class="container row">
  <div class="col l6 s12" id="infoCard">
    <div class="card panel">
      <h5 class="address" id="address"> <%= @property.streetaddress %></h5>
      <h5 class="address"> <%= @property.city %>, <%= @property.state %></h5>
      <br>
      <h5 id="specs" class="specs">Price: <%= @property.price %></h5>
      <br>
      <h5 id="specs" class="specs"><%= @property.spec %> </h5>
      <br>
      <h5 class="specs" id="specs">Square Ft: <%= @property.sqft %></h5>
    </div>
  </div>
</div>

<div class="container row">
  <div class="col l6 s12" id="reviews">
    <div class="card-panel">
<h3 id="propReviews">Property Reviews </h3>
<button class="btn" id="propRoute">
<%= link_to "Review Property", new_property_review_path(@property[:id])%>
</button>
<% @review.each do |review| %>
<div class="container row">
  <div class="col l1 s2">
   <%= link_to like_reviews_path(review), method: :put, class: "fa fa-angle-up fa-3x", 'aria-hidden' => true do %>
    <%= review.get_upvotes.size %>
    <% end %>

    <%= link_to dislike_reviews_path(review), method: :put, class: "fa fa-angle-down fa-3x", 'aria-hidden' => true do %>
    <%= review.get_downvotes.size %>
    <% end %>
  </div>
<div class="card-panel" id="reviewCards">
  <div class="card-title">
    <h6><a href="/users/<%= review.user_id %>" class="button-link"> <%= review.user.first_name %> <%= review.user.last_name %></a></h6>
    <strong><a href="/properties/<%= @property.id %>/reviews/<%= review.id %>" class="button-link"><%= review.title %></a></strong>
  </div>
  <div class="card-content">
  <p><%= review.text %></p>
</div>
<div class="card-action">
  <p><a href="#" id="edit">edit</a></p>

  <p><a href="#" id="delete">delete</a></p>
</div>
</div>
</div>
<% end %>
</div>
</div>
</div>

rentApp/app/views/reviews/_new.html.erb
<div class="container">
  <div class="card-panel">
    <%= form_for @review, url: "/properties/#{@property.id}/reviews" do |f| %>
    <h2><%= @property.streetaddress %></h2>
    <div>
      <%= f.text_field :title, placeholder: "Title" %>
    </div>
    <div>
      <%= f.text_field :text, placeholder: "What did you think of this place?" %>
    </div>

    <br>
    <%= f.submit "Post", :class => "button" %>
    <br>

    <% end %>
  </div>
</div>

rentApp/app/views/reviews/edit.html.erb
<div class="card-panel">
  <%= form_for @review do |f| %>
  <h4 class="card-panel">Edit Review</h4>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.text_field :text %>
  </div>

  <br>
  <%= f.submit "Update" %>
</div>
<% end %>

rentApp/app/views/reviews/new.html.erb
<div class="container">
  <div class="card-panel">
    <%= form_for @review, url: "/properties/#{@property.id}/reviews" do |f| %>
    <h3><%= @property.streetaddress %></h3>
    <div>
      <%= f.text_field :title, placeholder: "Title" %>
    </div>
    <div>
      <%= f.text_field :text, placeholder: "What did you think of this place?" %>
    </div>

    <br>
    <%= f.submit "Post", :class => "button" %>
    <br>

    <% end %>
  </div>
</div>

rentApp/app/views/reviews/show.html.erb
<div class="container">
  <div class="card-panel">
    <div class="header card-panel">
      <h3><%= @review.title %></h3>
      <p>
        <strong><a href="/users/<%= @review.user_id %>"><%= @review.user.first_name %> <%= @review.user.last_name %></a>
        <br>
        <a href="/properties/<%= @review.property_id %>"><%= @review.property.streetaddress %> </a> <br>
        <%= @review.created_at.strftime("%b %d, %Y") %></strong>
      </p>
    </div>
    <p class="flow-text">
      <%= @review.text %>
    </p>

    <% if can? :manage, @review %>

    <div>
      <form action='/reviews/<%= @review.id %>/edit' method='get'>
        <button>Edit</button>
      </form>
    </div>

    <%= button_to "Delete", property_review_path(@review.property.id, @review.id), method: :delete %>

  </div>
  <% end %>

</div>

rentApp/app/views/users/edit.html.erb
<h1>Editing User</h1>

<div class="container">
  <%= form_for @user do |f| %>

  <div>
   <%= f.file_field :avatar %>
  </div>
  <div>
  <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
  <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
  <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.text_field :hometown, placeholder: "Location" %>
  </div>
  <br>
  <%= f.submit "Update Profile" %>

  <% end %>

</div>

rentApp/app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for @user do |f| %>

   <%= f.text_field :first_name, placeholder: "First Name" %>
   <%= f.text_field :last_name, placeholder: "Last Name" %>
   <%= f.text_field :email, placeholder: "Email Address" %>
   <%= f.password_field :password, placeholder: "Password" %>
   <%= f.password_field :password_confirmation, placeholder: "Password" %>
   <%= f.submit "Create Account", :class => "button" %>

<% end %>

rentApp/app/views/users/show.html.erb
<section id="coverphoto">
  <div class="container row">
<div class="col l12 s12">
  <div class="card-panel" id="topPhoto">
  <img src="<%= @user.img %>" id="covPic">
</div>
</div>
</div>
</section>

<div class="container row">
  <div class="col l12" id="bodypanel">
  <div class="card-panel">

    <div class="container row">
      <div class="col l6 s12">
        <div class="card-image">
        <h4 id="hey">Hey <%= @user.first_name %></h4>
        <img src='http://www.net4surf.com/wp-content/uploads/2014/05/kanye-west-rappers-net-worth6.jpg' class="profphoto")></img>
      </div>
    </div>
      <% if current_user.id == @user.id %>
      <button class="btn updateProf">
        <a href='/users/<%=@user.id %>/edit' class="button-link">Update Profile</a>
      </button>
      <% end %>
      <br>
    </div>

      <div class="container">
        <div class="col l6 s12" id="infoProf">
          <div class="card-panel">
          <div>
          <h4><%= @user.first_name %> <%= @user.last_name %>
          </div>
          <div>
            Email: <%= @user.email %>
          </div>
          <br>
          <div>
            Hometown: <%= @user.hometown %>
          </div>
          <br>
          <div>
            Social Media: <a href='<%= @user.sociallink %>'><%= @user.sociallink %></a>
          </div>
        </div>
      </div>
    </div>

    <div class="container row">
      <div class="col l6 s12" id="reviewPanel">
        <div class="card-panel">
    <h3 id="propReviews">Property Reviews </h3>
    <button class="btn" id="propRoute">
    <%= link_to "Search Properties", properties_path %>
    </button>
    <% @reviews.each do |review| %>
    <div class="container row">
    <div class="card-panel" id="reviewCard">
      <div class="card-title">
        <h6><a href="/properties/<%= review.property_id %>" class="button-link"> <%= review.property.streetaddress %></a></h6>
        <strong><%= review.title %></strong>
      </div>
      <div class="card-content">
      <p><%= review.text %></p>
    </div>
    <div class="card-action">
      <p><a href="#" id="edit">edit</a></p>
      <p><a href="#" id="delete">delete</a></p>
    </div>
    </div>
    </div>
    <% end %>
    </div>
    </div>
    </div>
  </div>